#!/usr/bin/env bash
# Generate docker/livekit.prod.yaml from server .env (never commit the output).
# Safe for public repos: secrets stay on the host only.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.env}"
OUT="$ROOT/docker/livekit.prod.yaml"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — create production .env on the server (do not commit it)." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
# Only export the keys we need (avoid sourcing arbitrary shell)
LIVEKIT_API_KEY="$(grep -E '^LIVEKIT_API_KEY=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '\r' | sed 's/^["'\'']//;s/["'\'']$//')"
LIVEKIT_API_SECRET="$(grep -E '^LIVEKIT_API_SECRET=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '\r' | sed 's/^["'\'']//;s/["'\'']$//')"
LIVEKIT_NODE_IP="$(grep -E '^LIVEKIT_NODE_IP=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '\r' | sed 's/^["'\'']//;s/["'\'']$//' || true)"
set +a

if [[ -z "${LIVEKIT_API_KEY:-}" || -z "${LIVEKIT_API_SECRET:-}" ]]; then
  echo "LIVEKIT_API_KEY and LIVEKIT_API_SECRET must be set in $ENV_FILE" >&2
  exit 1
fi

# Reject obvious placeholders / example values from the public repo
case "$LIVEKIT_API_KEY|$LIVEKIT_API_SECRET" in
  *change-me*|*change_me*|*APIdracorddevkey*|*REPLACE_WITH*|*dracord_livekit_dev*)
    echo "Refusing placeholder LiveKit credentials — set strong production secrets in .env" >&2
    exit 1
    ;;
esac

if [[ ${#LIVEKIT_API_SECRET} -lt 32 ]]; then
  echo "LIVEKIT_API_SECRET must be at least 32 characters" >&2
  exit 1
fi

NODE_IP_LINE=""
if [[ -n "${LIVEKIT_NODE_IP:-}" ]]; then
  NODE_IP_LINE="  node_ip: \"${LIVEKIT_NODE_IP}\""
fi

umask 077
cat >"$OUT" <<EOF
# AUTO-GENERATED by docker/generate-livekit-prod.sh — do not commit
port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true
${NODE_IP_LINE}
logging:
  level: info
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
EOF

chmod 600 "$OUT"
echo "==> Wrote $OUT (mode 600)"
