/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#11131e',
        surface: '#11131e',
        'surface-dim': '#11131e',
        'surface-bright': '#373845',
        'surface-container-lowest': '#0b0e18',
        'surface-container-low': '#191b26',
        'surface-container': '#1d1f2b',
        'surface-container-high': '#272935',
        'surface-container-highest': '#323440',
        'surface-variant': '#323440',
        'on-surface': '#e1e1f1',
        'on-surface-variant': '#ccc3d3',
        'on-background': '#e1e1f1',
        primary: '#d7baff',
        'primary-container': '#bd93f9',
        'on-primary': '#411478',
        'on-primary-container': '#4e2484',
        secondary: '#b5c5fc',
        'secondary-container': '#374776',
        'on-secondary': '#1d2e5c',
        'on-secondary-container': '#a7b7ed',
        tertiary: '#ffafd7',
        'tertiary-container': '#fe78c5',
        'on-tertiary': '#620044',
        'on-tertiary-container': '#770054',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#968e9c',
        'outline-variant': '#4a4451',
        // Dracula classic aliases
        dracula: {
          bg: '#282a36',
          'bg-dark': '#21222c',
          'bg-darker': '#1e1f29',
          current: '#44475a',
          fg: '#f8f8f2',
          comment: '#6272a4',
          purple: '#bd93f9',
          pink: '#ff79c6',
          cyan: '#8be9fd',
          green: '#50fa7b',
          orange: '#ffb86c',
          red: '#ff5555',
          yellow: '#f1fa8c',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        gutter: '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['1.5rem', { lineHeight: '1.875rem', fontWeight: '700' }],
        'headline-lg': ['1.25rem', { lineHeight: '1.625rem', fontWeight: '600' }],
        'headline-md': ['1rem', { lineHeight: '1.375rem', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.125rem', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        float: '0 8px 24px rgba(0,0,0,0.45)',
        bar: '0 1px 2px rgba(0,0,0,0.20)',
      },
    },
  },
};
